language: python

cache: pip

addons:
  postgresql: "9.4"

services:
- postgresql
- redis-server

python:
- '3.5'
- '3.6-dev'
- 'nightly'

install:
- pip install -U -e .[all]
- pip install -U -r tests/requirements.txt

script:
- flake8 em2/ tests/
- pytest em2 --isort -p no:sugar -q --cache-clear
- py.test --cov=em2 --isort

after_success:
- coverage combine
- bash <(curl -s https://codecov.io/bash)
