language: python

cache: pip

addons:
  postgresql: "9.4"

services:
  - postgresql
  - redis-server

python:
  - "3.5"

install:
  # while arq is changing a lot, install it straight from commit
  - pip install git+git://github.com/samuelcolvin/arq.git@7812602375b8bd9790bf26add0f17bd29def5111
  - pip install -U -e .[all]
  - pip install -U -r tests/requirements.txt

script:
  - flake8 em2/ tests/
  - ./tests/isort_test.sh
  - py.test --cov=em2

after_success:
  - codecov
