dist: trusty
language: python
cache: pip
addons:
  postgresql: '9.5'
services:
- postgresql
- redis-server

python:
- '3.5'
- '3.6-dev'
- 'nightly'

matrix:
  allow_failures:
  - python: 'nightly'

install:
- pip install -U -e .[all]
- pip install -U -r tests/requirements.txt

script:
- python setup.py check -rms
- flake8 em2/ tests/
- pytest em2 -p no:sugar -q --cache-clear
- pytest --cov=em2

after_success:
- coverage combine
- bash <(curl -s https://codecov.io/bash)
