dist: trusty
language: python
cache: pip
addons:
  postgresql: '9.6'
services:
- postgresql
- redis-server

python:
- '3.6'
- '3.6-dev'
- 'nightly'  # currently 3.7

matrix:
  allow_failures:
  - python: '3.6-dev'
  - python: 'nightly'

install:
- pip install -U -r tests/requirements.txt
- pip install -e .

script:
- python setup.py check -rms
- flake8 em2/ tests/
- pytest em2 -p no:sugar -q --cache-clear
- pytest --cov=em2

after_success:
- coverage combine
- bash <(curl -s https://codecov.io/bash)

env:
  global:
    secure: "ikTi5uLBlQJSqUK5bQLquY5hBAMTOgXJOY3Ks/h4NQ8iuBBfQrRRFLAQqXsvWnNicqG/QNx9KGstSP1EEBdZxyg3+EPoIXduAOUxo0Nww7bsU9fc387lEOfMpfrNUmWoP9okZi/0nG5aSbDBmGBYCft3zW2xexKHodVOFfOiMQuRzDh5PuWu3l/7jxQNY6ropo9djXn8wuWV/80GWu+A4WzJmYXme3PLPwgktkS3r7IVGfnK4nyYbOxxca5d4jo715ki+0jQ57wYlFG03w67ATq6H1iOzvIJMojsQ9jumRhCEFLAmViNTQfmCJsYMBAvMLFSz3Fz6+S2CDPMf8NovCVdctE4BiC34hrMJkutBeO7e1HoATTbGXlPwmnndxRgS64EPKWCMM7syUvAKYZUO3EcYy12qqkM77vtttv0jy7ZQy6KS1CnmDh2No/JaPqbgnlooRXvOAEUbI1UfrmhHASqT1LnqDCnf0xVonoM8GZlk3A0lBNdP8JMdaQ7SFvEDtMrLaVsh64lJ47abZXW5oNAMP6M5lgBRHMwIsifr+Zq186MqdjiZl5cSjr0ow+ah7xQi56EeghD/5wK20V2Rcukyzl+RBRB+VvKmSuj/JGtJqOWsOz/tTWalOxVTlktbipUtJ6GOLgbl8ffHLSnPlskkPyO3lhABZQudVp9maM="
