language: python

cache: pip

addons:
  postgresql: "9.4"

services:
  - postgresql
  - redis-server

python:
  - "3.5"

install:
  # while arq is changing a lot, install it straight from commit
  - pip install git+git://github.com/samuelcolvin/arq.git@3fe4e14930aafb971044dca80a838a3958c622ee
  - pip install -U -e .[all]
  - pip install -U -r tests/requirements.txt

script:
  - flake8 em2/ tests/
  - py.test --cov=em2

after_success:
  - codecov
