language: python

cache: pip

addons:
  postgresql: "9.4"

services:
  - postgresql
  - redis-server

python:
  - "3.5"

install:
  - pip install -e .[all]
  - pip install -U -r tests/requirements.txt

script:
  - flake8 em2/ tests/
  - py.test --cov=em2

after_success:
  - codecov
