version: '3.2'

volumes:
  postgres: {}
  redis: {}

networks:
  default:
    driver: bridge
    ipam:
      config:
      - subnet: 172.20.0.0/16

services:
  logs:
    image: gliderlabs/logspout
    environment:
      SYSLOG_HOSTNAME: 'em2'
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    ports:
    - 5001:80

  postgres:
    image: postgres:9.6
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
    volumes:
    - postgres:/var/lib/postgresql/data
    depends_on:
    - logs

  redis:
    image: redis:3.0-alpine
    volumes:
    - redis:/data
    restart: always
    depends_on:
    - logs

  nginx:
    image: nginx:1.13-alpine
#    restart: always
    volumes:
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
    - 8000:80
    depends_on:
    - logs

  web:
    image: em2
    environment:
      EM2_COMMAND: web
      EM2_DEBUG: 'true'
      EM2_PG_HOST: postgres
      EM2_PG_PASSWORD: docker
      EM2_R_HOST: redis
      EM2_LOCAL_DOMAIN: ${EM2_LOCAL_DOMAIN}
      EM2_SECRET_SESSION_KEY: ${EM2_SECRET_SESSION_KEY}
      EM2_COMMS_PROTO: ${EM2_COMMS_PROTO}
    restart: always
    networks:
      default:
        ipv4_address: 172.20.0.101
    depends_on:
    - postgres
    - redis
    - logs

  worker:
    image: em2
    environment:
      EM2_COMMAND: worker
      EM2_DEBUG: 'true'
      EM2_PG_HOST: postgres
      EM2_PG_PASSWORD: docker
      EM2_R_HOST: redis
      EM2_LOCAL_DOMAIN: ${EM2_LOCAL_DOMAIN}
      EM2_SECRET_SESSION_KEY: ${EM2_SECRET_SESSION_KEY}
      EM2_COMMS_PROTO: ${EM2_COMMS_PROTO}
    restart: always
    depends_on:
    - postgres
    - redis
    - logs
